# Generated by Django 6.0.2 on 2026-02-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
