# Generated by Django 6.0.2 on 2026-02-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe_instructions_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
