# Generated by Django 6.0.2 on 2026-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_step_recipe_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(blank=True, to='core.step'),
        ),
    ]
