# Generated by Django 6.0.2 on 2026-02-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_recipe_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='description',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='step',
            new_name='step_number',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
    ]
