# Generated by Django 6.0.2 on 2026-02-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_description_step_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chefs_tip',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
