# Generated by Django 6.0.2 on 2026-03-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_recipe_chefs_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='access_history',
            field=models.ManyToManyField(related_name='users', to='core.accesshistory'),
        ),
    ]
