# Generated by Django 6.0.3 on 2026-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_accesshistory_user_access_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_history',
            field=models.ManyToManyField(related_name='user', to='core.accesshistory'),
        ),
    ]
